### ISSUE TITLE
Configurable shortcuts

### ISSUE THREAD

**Issue by danifr** [TsunDoge/spotify-hotkeys-firefox#1]
First thanks for this amazing addon this is exactly what I was looking for 🥇 👍 
Any plans of adding the option to allow the usesr to specify their own shortcuts?

Thanks a lot again!

**Comment by TsunDoge** [comment]
First of all, thank you for your kind words. ^^

Answering the question, yes. Actually I'm trying to implement it but it's my first addon and I'm having problems storing the user preferences and make the addon recognize the custom shortcuts.

**Comment by TsunDoge** [comment]
New approach with customizable shortcuts until [mozilla implemets UI for shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384)

**Comment by p-p-q** [comment]
Thank you for creating this. It does what I want and nothing more, that's how everything should be.
Can you give me a hint on how to build a .xpi file from the contents of this repo? I changed the hotkeys in the .json file so I need to rebuild.

**Comment by TsunDoge** [comment]
@p-p-q glad I was able to help you. 

Since still there is no official way to costumize shortcuts I recommend you to use the master branch and change there the keys on the .json file. The development branch is just a "temporary workaround" and needs improvements.

The .xpi is just a compressed file so for the build just compress the repository into one file with one of the following extensions: .zip, .xpi, .crx, .xml.

**Comment by p-p-q** [comment]
@TsunDoge Thanks, I tried to do this. I took all the files from this repo, edited the .json and put everything in a .zip. However, Firefox will not install it and says it is damaged? Maybe something is missing?

**Comment by TsunDoge** [comment]
That's probably because you have misconfigured the shortcuts or some of them are used by the explorer.
Try others keycombos to check if that's the issue. @p-p-q

**Comment by p-p-q** [comment]
@TsunDoge I tried again with your unmodified .json, it gives me the same error message. The .xpi you uploaded to addons.mozilla.org has a META-INF directory, is that required?

**Comment by TsunDoge** [comment]
The META-INF directory it is not needed. The original files should not give you any error.

Try again downloading the project, then decompress it and visit _about:debugging_, click on "load temporary addon", and finally select the manifest.json file.
Firefox should load the addon correctly.

**Comment by TsunDoge** [comment]
I reopen this issue due to mozilla [providing a method to change the webextensions shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811)

Also found an [interesting library](https://github.com/piroor/webextensions-lib-shortcut-customize-ui) which build a custom UI which I'll use until a similar one is land on Firefox by default.
