### ISSUE TITLE
don't propagate hotkey to current website

### ISSUE THREAD

**Issue by SpineEyE** [TsunDoge/spotify-hotkeys-firefox#10]
I defined hotkeys that have functionality on some websites and I would like to prevent that the hotkeys are also triggering that action on the website that is currently opened in Firefox. Is this possible?

**Comment by TsunDoge** [comment]
Hi SpineEye,

I am not getting what is your issue here. Do you want to block the custom Spotify shortcuts in some websites or block other hotkeys that you have which are in conflict with the Spotify ones?

**Comment by SpineEyE** [comment]
Hey,
I just figured this might be a Firefox restriction, I think it's better explained with an example: I have assigned one shortcut to shift+alt+x. When I press these keys while I'm on Wikipedia, instead of playing the next song, Wikipedia shows me a random article since this is apparently their hotkey for it. But I don't want their function to be executed, I just want to play the next song.

**Comment by TsunDoge** [comment]
Hi,
Thank you for the example, now I understand what you are asking.

In the first place, I need to explain something: it is "theoricaly possible" to stop the propragation of the hoykeys/events but it is not really recommendable. In short, if, for example, the propagation of a shortcut stops, bugs and unexpected events can occur, since the events are global objects and the external code can depend on them. [Dangers of Stopping Event Propragation](https://css-tricks.com/dangers-stopping-event-propagation/)

For the moment, I do not consider it appropriate to manage such cases for possible failures that may cause.
That said, I would recommend that you change the hotkey to another one that does not cause trouble.

I am sorry I can not be more helpful.

**Comment by TsunDoge** [comment]
Using the default hotkeys (alt+shift) I have never encountered a conflict.
Also, as I said before, I am totally against interfering with the behavior of other websites if it is not essential.
However, I will look at some possible solution but I do not promise anything.
