### ISSUE TITLE
Not working on Mozilla Firefox 66.0.3

### ISSUE THREAD

**Issue by pintify** [TsunDoge/spotify-hotkeys-firefox#15]
I've recently updated Mozilla Firefox to 66.0.3 and the add-on stopped working. Firefox help redirects me to an [article about add-ons signing](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox), which I imagine is the cause of the failure.

Is there an intention to support new versions?

**Comment by TsunDoge** [comment]
Hi,

This is very weird because the addon is signed, so it should work. Also, I am running Firefox version 67.0 and it works well.
I suggest to update the Firefox version due to some issues discovered on that particular version [add-ons-disabled-or-fail-to-install-firefox](https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox).

**Comment by pintify** [comment]
Indeed, I've updated to version 66.0.4 and worked like a charm. Thank you for everything!
