### ISSUE TITLE
option to open spotify or not is not saved

### ISSUE THREAD

**Issue by Geobert** [TsunDoge/spotify-hotkeys-firefox#9]
Hi!

It seems that the tick box is not saved across Firefox sessions.

**Comment by TsunDoge** [comment]
Right now I am using the local storage so the settings are local to the machine the extension was installed on.
The reason for choosing it is because I previously tried to use the sync API but found some issues with the gecko-id. Despite this it is true that it would be great to share settings between sessions. I will investigate more.

Enhancement #8 sync API instead of local storage

**Comment by Geobert** [comment]
When I said "session" I mean launching firefox.

On the same computer :-/

**Comment by TsunDoge** [comment]
Oh. Thought you were trying to sync the settings across multiple machines using a firefox/google account. Then it's a bug. Let me check it.

**Comment by TsunDoge** [comment]
My fault, I was writing the default settings each time the browser started.

The following commits should fix it and also I changed to the sync storage. Thanks for your feedback.
